version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chinook
      POSTGRES_USER: chinook_user
      POSTGRES_PASSWORD: chinook_password
    ports:
      - "5432:5432"
    volumes:
      - ./chinook_init.sql:/docker-entrypoint-initdb.d/chinook_init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chinook_user -d chinook"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: